export const formKeys = {
    choices: 'choices',
    rounds: 'rounds',
    phases: 'phases',
    conditions: 'conditions',
    stages: 'stages',
    fields: 'fields',
    actions: 'actions',
    factions: 'factions',
    tokens: 'tokens',
    slots: 'slots',
    paths: 'paths',
    teams: 'teams',
    games: 'games',
    images: 'images',
    keywords: 'keywords',
    styles: 'styles',
    sounds: 'sounds',
    states: 'states',
    expressions: 'expressions',
    animations: 'animations',
    handlers: 'handlers',
    setups: 'setups',
}

export type FormKey = keyof typeof formKeys;