export const actionTypes = {
    SHOW_PAGE_LOADER: 'SHOW_PAGE_LOADER',
    OPERATION_SUCCESS: 'OPERATION_SUCCESS',
    OPERATION_FAIL: 'OPERATION_FAIL',
    MARK_PRELOADED_GAME: 'MARK_PRELOADED_GAME',
    ADD_GAME_ASSETS: 'ADD_GAME_ASSETS',
};
