export const actionTypes = {
    SHOW_PAGE_LOADER: 'SHOW_PAGE_LOADER',
    OPERATION_SUCCESS: 'OPERATION_SUCCESS',
    OPERATION_FAIL: 'OPERATION_FAIL',

    ADD_GAME_ASSETS: 'ADD_GAME_ASSETS',

    GET_GAMES: 'GET_GAMES',
    SET_GAMES: 'SET_GAMES',
    GET_GAMES_SUCCESS: 'GET_GAMES_SUCCESS',
    GET_GAMES_FAIL: 'GET_GAMES_FAIL'
};
