export const actionTypes = {
    SHOW_PAGE_LOADER: 'SHOW_PAGE_LOADER',
    OPERATION_SUCCESS: 'OPERATION_SUCCESS',
    OPERATION_FAIL: 'OPERATION_FAIL',

    LOGOUT: 'LOGOUT',
    GET_CURRENT_USER: 'GET_CURRENT_USER',
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    GET_CURRENT_USER_SUCCESS: 'GET_CURRENT_USER_SUCCESS',
    GET_CURRENT_USER_FAIL: 'GET_CURRENT_USER_FAIL',

    FETCH_ACTIVE_GAMES: 'FETCH_ACTIVE_GAMES',
    FETCH_ACTIVE_GAMES_SUCCESS: 'FETCH_ACTIVE_GAMES_SUCCESS',
    FETCH_ACTIVE_GAMES_FAIL: 'FETCH_ACTIVE_GAMES_FAIL',

    ADD_ACTIVE_GAME: 'ADD_ACTIVE_GAME',
};
