export const actionTypes = {
    FETCH_GAME_INSTANCE: '[Arena] FETCH_GAME_INSTANCE',
    FETCH_GAME_INSTANCE_SUCCESS: '[Arena] FETCH_GAME_INSTANCE_SUCCESS',
    FETCH_GAME_INSTANCE_FAIL: '[Arena] FETCH_GAME_INSTANCE_FAIL',

    FETCH_GAME: '[Arena] FETCH_GAME',
    FETCH_GAME_SUCCESS: '[Arena] FETCH_GAME_SUCCESS',
    FETCH_GAME_FAIL: '[Arena] FETCH_GAME_FAIL',

    FETCH_GAME_CONFIG: '[Arena] FETCH_GAME_CONFIG',
    FETCH_GAME_CONFIG_SUCCESS: '[Arena] FETCH_GAME_CONFIG_SUCCESS',
    FETCH_GAME_CONFIG_FAIL: '[Arena] FETCH_GAME_CONFIG_FAIL',

    INITIALIZE_GAME_STATE: '[Arena] CREATE_GAME_STATE',
    SET_GAME_STATE: '[Arena] SET_GAME_STATE',
} as const;