export const actionTypes = {
    FETCH_ACTIVE_GAME: '[Arena] FETCH_ACTIVE_GAME',
    FETCH_ACTIVE_GAME_SUCCESS: '[Arena] FETCH_ACTIVE_GAME_SUCCESS',
    FETCH_ACTIVE_GAME_FAIL: '[Arena] FETCH_ACTIVE_GAME_FAIL',

    FETCH_GAME_CONFIG: '[Arena] FETCH_GAME_CONFIG',
    FETCH_GAME_CONFIG_SUCCESS: '[Arena] FETCH_GAME_CONFIG_SUCCESS',
    FETCH_GAME_CONFIG_FAIL: '[Arena] FETCH_GAME_CONFIG_FAIL',
};