export const PRIMITIVE_TYPES = {
    SPRITE: 'SPRITE',
    CIRCLE: 'CIRCLE',
    LINE: 'LINE',
    RECTANGLE: 'RECTANGLE',
    IMAGE: 'IMAGE',
    SOUND: 'SOUND',
    COLLECTION: 'COLLECTION',
    CONTAINER: 'CONTAINER'
};