export const QUEST_CONDITIONS = {
    CLAIM_FIELDS: 'CLAIM_FIELDS'
};

export const QUEST_AWARDS = {
    RESOURCE: 'RESOURCE',
    FIELD: 'FIELD',
    QUEST: 'QUEST',
    ACTIVITY: 'ACTIVITY'
};

export const QUEST_COSTS = {
    RESOURCE: 'RESOURCE',
    ACTIVITY: 'ACTIVITY',
    RANDOM_ACTIVITY: 'RANDOM_ACTIVITY',
    QUEST: 'QUEST',
    RANDOM_QUEST: 'RANDOM_QUEST',
    FIELD: 'FIELD',
    RANDOM_FIELD: 'RANDOM_FIELD'
};

export const QUEST_PENALTIES = {
    RESOURCE: 'RESOURCE',
    ACTIVITY: 'ACTIVITY',
    RANDOM_ACTIVITY: 'RANDOM_ACTIVITY',
    QUEST: 'QUEST',
    RANDOM_QUEST: 'RANDOM_QUEST',
    FIELD: 'FIELD',
    RANDOM_FIELD: 'RANDOM_FIELD'
};


export type QuestCondition =
    typeof QUEST_CONDITIONS.CLAIM_FIELDS;
