export const QUEST_CONDITIONS = {
    CLAIM_FIELD: 'CLAIM_FIELD',
    CLAIM_ANY_FIELDS: 'CLAIM_ANY_FIELDS',

    DEFEND_ANY_FIELDS: 'DEFEND_FIELDS',
    DEFEND_FIELD: 'DEFEND_FIELD',

    CLAIM_RESOURCE: 'CLAIM_RESOURCE',
    CLAIM_ANY_RESOURCE: 'CLAIM_ANY_RESOURCE',

    PLAY_ACTIVITY: 'PLAY_ACTIVITY',
    PLAY_ANY_ACTIVITY: 'PLAY_ANY_ACTIVITY',
    STEAL_ACTIVITY: 'STEAL_ACTIVITY',
    STEAL_ANY_ACTIVITY: 'STEAL_ANY_ACTIVITY',
    DISCARD_ACTIVITY: 'DISCARD_ACTIVITY',
    DISCARD_ANY_ACTIVITY: 'DISCARD_ANY_ACTIVITY'
};

export const QUEST_COSTS = {
    RESOURCE: 'RESOURCE',
    ACTIVITY: 'ACTIVITY',
    QUEST: 'QUEST',
    FIELD: 'FIELD',
};

export const QUEST_OUTCOMES = {
    RESOURCE: 'RESOURCE',
    RANDOM_RESOURCE: 'RANDOM_RESOURCE',
    ACTIVITY: 'ACTIVITY',
    RANDOM_ACTIVITY: 'RANDOM_ACTIVITY',
    QUEST: 'QUEST',
    RANDOM_QUEST: 'RANDOM_QUEST',
    FIELD: 'FIELD',
    RANDOM_FIELD: 'RANDOM_FIELD'
};


export type QuestConditionTypes =
    typeof QUEST_CONDITIONS.CLAIM_FIELD;
