export const CLEAR_FORM = 'CLEAR_FORM';
export const UPDATE_FIELD = 'UPDATE_FIELD';

export const SAVE_CHARACTER = 'SAVE_CHARACTER';
export const SAVE_CHARACTER_SUCCESS = 'SAVE_CHARACTER_SUCCESS';
export const SAVE_CHARACTER_FAIL = 'SAVE_CHARACTER_FAIL';

export const SAVE_TRIVIA = 'SAVE_TRIVIA';
export const SAVE_TRIVIA_SUCCESS = 'SAVE_TRIVIA_SUCCESS';
export const SAVE_TRIVIA_FAIL = 'SAVE_TRIVIA_FAIL';

export const UPDATE_EDITOR_ASSET = 'UPDATE_EDITOR_ASSET';

export const SAVE_FIELD = 'SAVE_FIELD';
export const SAVE_FIELD_SUCCESS = 'SAVE_FIELD_SUCCESS';
export const SAVE_FIELD_FAIL = 'SAVE_FIELD_FAIL';

export const DELETE_FIELD = 'DELETE_FIELD';
export const DELETE_FIELD_SUCCESS = 'DELETE_FIELD_SUCCESS';
export const DELETE_FIELD_FAIL = 'DELETE_FIELD_FAIL';

export const GET_FIELDS = 'GET_FIELDS';
export const GET_FIELDS_SUCCESS = 'GET_FIELDS_SUCCESS';
export const GET_FIELDS_FAIL = 'GET_FIELDS_FAIL';

export const ADD_GRID_FIELD = 'ADD_GRID_FIELD';
export const REMOVE_GRID_FIELD = 'REMOVE_GRID_FIELD';

export const ADD_GRID_ROW = 'ADD_GRID_ROW';
export const ADD_GRID_COLUMN = 'ADD_GRID_COLUMN';
export const REMOVE_GRID_ROW = 'REMOVE_GRID_ROW';
export const REMOVE_GRID_COLUMN = 'REMOVE_GRID_COLUMN';

export const CREATE_GAME = 'CREATE_GAME';
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';
export const CREATE_GAME_FAIL = 'CREATE_GAME_FAIL';

export const GET_GAMES = 'GET_GAMES';
export const GET_GAMES_SUCCESS = 'GET_GAMES_SUCCESS';
export const GET_GAMES_FAIL = 'GET_GAMES_FAIL';

export const UPDATE_MAP = 'UPDATE_MAP';

export const DELETE_MAP_LOCATION = 'DELETE_MAP_LOCATION';
export const DELETE_MAP_LOCATION_SUCCESS = 'DELETE_MAP_LOCATION_SUCCESS';
export const DELETE_MAP_LOCATION_FAIL = 'DELETE_MAP_LOCATION_FAIL';

export const TOGGLE_FIELD_EDITOR = 'TOGLE_FIELD_EDITOR';
export const CHANGE_SELECTED_FIELD = 'CHANGE_SELECTED_FIELD';
export const TOGGLE_PATH_CREATION_MODE = 'TOGGLE_PATH_CREATION_MODE';

export const SAVE_MAP_LOCATION = 'SAVE_MAP_LOCATION';
export const SAVE_MAP_LOCATION_SUCCESS = 'SAVE_MAP_LOCATION_SUCCESS';
export const SAVE_MAP_LOCATION_FAIL = 'SAVE_MAP_LOCATION_FAIL';

export const GET_MAP_LOCATIONS = 'GET_MAP_LOCATIONS';
export const GET_MAP_LOCATIONS_SUCCESS = 'GET_MAP_LOCATIONS_SUCCESS';
export const GET_MAP_LOCATIONS_FAIL = 'GET_MAP_LOCATIONS_FAIL';

export const SAVE_MAP_PATH = 'SAVE_MAP_PATH';
export const SAVE_MAP_PATH_SUCCESS = 'SAVE_MAP_PATH_SUCCESS';
export const SAVE_MAP_PATH_FAIL = 'SAVE_MAP_PATH_FAIL';

export const DELETE_MAP_PATH = 'DELETE_MAP_PATH';
export const DELETE_MAP_PATH_SUCCESS = 'DELETE_MAP_PATH_SUCCESS';
export const DELETE_MAP_PATH_FAIL = 'DELETE_MAP_PATH_FAIL';

export const GET_MAP_PATHS = 'GET_MAP_PATHS';
export const GET_MAP_PATHS_SUCCESS = 'GET_MAP_PATHS_SUCCESS';
export const GET_MAP_PATHS_FAIL = 'GET_MAP_PATHS_FAIL';

export const CHANGE_SELECTED_PATH = 'CHANGE_SELECTED_PATH';

export const SAVE_MAP = 'SAVE_MAP';
export const SAVE_MAP_SUCCESS = 'SAVE_MAP_SUCCESS';
export const SAVE_MAP_FAIL = 'SAVE_MAP_FAIL';

export const GET_MAP = 'GET_MAP';
export const GET_MAP_SUCCESS = 'GET_MAP_SUCCESS';
export const GET_MAP_FAIL = 'GET_MAP_FAIL';


// requests
export const SAVE_RESOURCE = 'SAVE_RESOURCE';
export const DELETE_RESOURCE = 'DELETE_RESOURCE';
export const GET_RESOURCES = 'GET_RESOURCES';

// commands
export const ADD_RESOURCE = 'ADD_RESOURCE';
export const REMOVE_RESOURCE = 'REMOVE_RESOURCE';
export const SET_RESOURCES = 'SET_RESOURCES';
export const TOGGLE_RESOURCE_EDITOR = 'TOGGLE_RESOURCE_EDITOR';

// events
export const SAVE_RESOURCE_SUCCESS = 'SAVE_RESOURCE_SUCCESS';
export const SAVE_RESOURCE_FAIL = 'SAVE_RESOURCE_FAIL';
export const DELETE_RESOURCE_SUCCESS = 'DELETE_RESOURCE_SUCCESS';
export const DELETE_RESOURCE_FAIL = 'DELETE_RESOURCE_FAIL';
export const GET_RESOURCES_SUCCESS = 'GET_RESOURCES_SUCCESS';
export const GET_RESOURCES_FAIL = 'GET_RESOURCES_FAIL';



