export const UPDATE_FIELD = 'UPDATE_FIELD';

export const SAVE_RESOURCE = 'SAVE_RESOURCE';
export const SAVE_RESOURCE_SUCCESS = 'SAVE_RESOURCE_SUCCESS';
export const SAVE_RESOURCE_FAIL = 'SAVE_RESOURCE_FAIL';

export const SAVE_CHARACTER = 'SAVE_CHARACTER';
export const SAVE_CHARACTER_SUCCESS = 'SAVE_CHARACTER_SUCCESS';
export const SAVE_CHARACTER_FAIL = 'SAVE_CHARACTER_FAIL';

export const SAVE_TRIVIA = 'SAVE_TRIVIA';
export const SAVE_TRIVIA_SUCCESS = 'SAVE_TRIVIA_SUCCESS';
export const SAVE_TRIVIA_FAIL = 'SAVE_TRIVIA_FAIL';

export const UPDATE_EDITOR_ASSET = 'UPDATE_EDITOR_ASSET';

export const SAVE_FIELD = 'SAVE_FIELD';
export const SAVE_FIELD_SUCCESS = 'SAVE_FIELD_SUCCESS';
export const SAVE_FIELD_FAIL = 'SAVE_FIELD_FAIL';

export const ADD_GRID_FIELD = 'ADD_GRID_FIELD';
export const REMOVE_GRID_FIELD = 'REMOVE_GRID_FIELD';

export const ADD_GRID_ROW = 'ADD_GRID_ROW';
export const ADD_GRID_COLUMN = 'ADD_GRID_COLUMN';
export const REMOVE_GRID_ROW = 'REMOVE_GRID_ROW';
export const REMOVE_GRID_COLUMN = 'REMOVE_GRID_COLUMN';

export const CREATE_GAME = 'CREATE_GAME';
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';
export const CREATE_GAME_FAIL = 'CREATE_GAME_FAIL';

