export const ROUTER_PARAMS = {
    GAME_ID: 'GAME_ID',
    WIDGET_ID: 'WIDGET_ID',
    NODE_ID: 'NODE_ID',
    NODE_HANDLER_ID: 'NODE_HANDLER_ID',
    NODE_LIFECYCLE_ID: 'NODE_LIFECYCLE_ID',
    MODULE_ID: 'MODULE_ID',
    SANDBOX_ID: 'SANDBOX_ID',
    VERSION_ID: 'VERSION_ID',

    SETUP_ID: 'SETUP_ID',
    LOBBY_NAME: 'LOBBY_NAME',
    GAME_INSTANCE_ID: 'GAME_INSTANCE_ID',

    ENTITY_ID: 'ENTITY_ID',
    NESTED_ENTITY_ID: 'NESTED_ENTITY_ID',
};
