export const ROUTER_PARAMS = {
    GAME_ID: 'GAME_ID',
    VERSION_ID: 'VERSION_ID',
    MODULE_ID: 'MODULE_ID',

    LOBBY_NAME: 'LOBBY_NAME',
    GAME_INSTANCE_ID: 'GAME_INSTANCE_ID',

    MODULAR_ENTITY_ID: 'MODULAR_ENTITY_ID',
    VERSIONED_ENTITY_ID: 'VERSIONED_ENTITY_ID',
    NESTED_ENTITY_ID: 'NESTED_ENTITY_ID',
    PARENT_ENTITY_ID: 'PARENT_ENTITY_ID',
};
