export const ROUTER_PARAMS = {
    GAME_ID: 'GAME_ID',
    WIDGET_ID: 'WIDGET_ID',
    NODE_ID: 'NODE_ID',
    MODULE_ID: 'MODULE_ID',
    SANDBOX_ID: 'SANDBOX_ID',
    VERSION_ID: 'VERSION_ID',

    SETUP_ID: 'SETUP_ID',
    LOBBY_NAME: 'LOBBY_NAME',
    GAME_INSTANCE_ID: 'GAME_INSTANCE_ID'
};
