export const controlTypes = {
    TEXT_INPUT: 'TEXT_INPUT',
    IMAGE_BROWSER: 'IMAGE_BROWSER',
    BUTTON_GROUP: 'BUTTON_GROUP',
    SLIDER: 'SLIDER',
    QUANTITY_PICKER: 'QUANTITY_PICKER',
    SWITCH: 'SWITCH',
    NESTED_FORM: 'NESTED_FORM'
};
