export const controlTypes = {
    TEXT_INPUT: 'TEXT_INPUT',
    NUMBER_INPUT: 'NUMBER_INPUT',
    IMAGE_BROWSER: 'IMAGE_BROWSER',
    BUTTON_GROUP: 'BUTTON_GROUP',
    SLIDER: 'SLIDER',
    SWITCH: 'SWITCH',
    DROPDOWN: 'DROPDOWN',


    NESTED_FORM: 'NESTED_FORM',
    DYNAMIC_NESTED_FORM: 'DYNAMIC_NESTED_FORM',
    FORM_ARRAY: 'FORM_ARRAY'
};
