export const controlTypes = {

    TEXT_INPUT: 'TEXT_INPUT',
    NUMBER_INPUT: 'NUMBER_INPUT',
    BUTTON_GROUP: 'BUTTON_GROUP',
    DROPDOWN: 'DROPDOWN',

    IMAGE_PICKER: 'IMAGE_PICKER',

    NESTED_FORM: 'NESTED_FORM',
    FORM_ARRAY: 'FORM_ARRAY'
};
